# Generated by Django 5.2.14 on 2026-06-09 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circles', '0002_circleinvite'),
    ]

    operations = [
        migrations.AddField(
            model_name='circle',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
