# Generated by Django 5.2.14 on 2026-06-13 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circles', '0003_circle_is_archived'),
    ]

    operations = [
        migrations.AddField(
            model_name='circle',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='circles/avatars/'),
        ),
        migrations.AddField(
            model_name='circle',
            name='cover_photo',
            field=models.ImageField(blank=True, null=True, upload_to='circles/covers/'),
        ),
    ]
