# Generated by Django 5.2.14 on 2026-06-01 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='memory',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='memories/photos/'),
        ),
    ]
