# Generated by Django 5.2.14 on 2026-06-06 00:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memories', '0005_memorycomment'),
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='memory',
            name='trip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='memories', to='trips.trip'),
        ),
    ]
